-- SQL-107585.sql --

CREATE TABLE produtos (
  id_produto INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome_produto VARCHAR(255) NOT NULL
);

CREATE TABLE vendas (
  id_venda INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data_venda DATE NOT NULL,
  id_produto INTEGER REFERENCES produtos(id_produto),
  quantidade INTEGER NOT NULL
);

INSERT INTO produtos (nome_produto) VALUES 
  ('Camiseta'), 
  ('Calça'), 
  ('Tênis');

INSERT INTO vendas (data_venda, id_produto, quantidade) VALUES
  ('2023-11-01', 1, 5), 
  ('2023-11-01', 2, 2), 
  ('2023-11-02', 1, 3), 
  ('2023-11-02', 3, 1), 
  ('2023-11-03', 2, 4);

SELECT * FROM produtos

SELECT * FROM vendas


CREATE OR REPLACE PROCEDURE relatorio_vendas_diarias(data_relatorio DATE)
LANGUAGE plpgsql
AS $$
DECLARE
  venda RECORD; 
BEGIN
  RAISE NOTICE 'Relatório de Vendas para o dia: %', data_relatorio;

  FOR venda IN 
    SELECT p.nome_produto, v.quantidade
    FROM vendas v
    JOIN produtos p ON v.id_produto = p.id_produto
    WHERE v.data_venda = data_relatorio
  LOOP
  
    RAISE NOTICE 'Produto: %, Quantidade: %', venda.nome_produto, venda.quantidade;
  END LOOP;
END;
$$;

CALL relatorio_vendas_diarias('2023-11-02'); 